apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-weather
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-weather
  template:
    metadata:
      labels:
        app: go-weather
    spec:
      containers:
      - name: go-weather-container
        image: go-weather:latest
        ports:
        - containerPort: 8080