apiVersion: v1
kind: Service
metadata:
  name: go-weather-service
spec:
  type: NodePort
  selector:
    app: go-weather
  ports:
    - protocol: TCP
      port: 8080        # service port, intern
      targetPort: 8080  # container port
      nodePort: 30000   # port for ext access